// <auto-generated />
using CoreMultiTenancy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMultiTenancy.Api.Data.Migrations
{
    [DbContext(typeof(TenantedDbContext))]
    partial class TenantedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreMultiTenancy.Api.Entities.Aircraft", b =>
                {
                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsGrounded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("RegNumber");

                    b.ToTable("Aircraft");
                });
#pragma warning restore 612, 618
        }
    }
}
