// <auto-generated />
using System;
using CoreMultiTenancy.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreMultiTenancy.Identity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220923042600_demo")]
    partial class demo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUri")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresConfirmationForNewUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77a5570f-3ce5-48ba-9461-80283ed1d94d"),
                            CreationDate = new DateTime(2022, 9, 23, 4, 25, 59, 544, DateTimeKind.Utc).AddTicks(8013),
                            IsActive = true,
                            LogoUri = "tenantlogo1.jpg",
                            OwnerUserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            RequiresConfirmationForNewUsers = false,
                            Title = "MyCompany"
                        },
                        new
                        {
                            Id = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            CreationDate = new DateTime(2022, 9, 23, 4, 25, 59, 544, DateTimeKind.Utc).AddTicks(8017),
                            IsActive = true,
                            LogoUri = "tenantlogo2.jpg",
                            OwnerUserId = new Guid("77a6570f-3ce5-48ba-9461-80283ed1d94d"),
                            RequiresConfirmationForNewUsers = false,
                            Title = "OtherCompany"
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Permission", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte>("PermCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VisibleToUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermCategoryId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = (byte)0,
                            Description = "",
                            IsObsolete = false,
                            Name = "",
                            PermCategoryId = (byte)0,
                            VisibleToUser = false
                        },
                        new
                        {
                            Id = (byte)1,
                            Description = "",
                            IsObsolete = false,
                            Name = "",
                            PermCategoryId = (byte)0,
                            VisibleToUser = false
                        },
                        new
                        {
                            Id = (byte)2,
                            Description = "Users with this permission can create new aircraft within the tenant.",
                            IsObsolete = false,
                            Name = "Create Aircraft",
                            PermCategoryId = (byte)1,
                            VisibleToUser = true
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.PermissionCategory", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VisibleToUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PermissionCategories");

                    b.HasData(
                        new
                        {
                            Id = (byte)0,
                            IsObsolete = false,
                            Name = "",
                            VisibleToUser = false
                        },
                        new
                        {
                            Id = (byte)1,
                            IsObsolete = false,
                            Name = "Aircraft",
                            VisibleToUser = true
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("OrgId");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("78a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            ConcurrencyStamp = "ba77433d-cc36-4960-9f82-c0850df8edd4",
                            Description = "Default admin role with all permissions.",
                            IsGlobal = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("77a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            ConcurrencyStamp = "b9caf510-4882-4156-95b0-7771682b1acb",
                            Description = "Default role with minimal permissions.",
                            IsGlobal = true,
                            Name = "Default",
                            NormalizedName = "DEFAULT"
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("78a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            PermissionId = (byte)1
                        },
                        new
                        {
                            RoleId = new Guid("77a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            PermissionId = (byte)0
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c45b3fb4-fa34-4801-816e-0a240aa1a62e",
                            Email = "admin@mydomain.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MYDOMAIN.COM",
                            NormalizedUserName = "ADMIN@MYDOMAIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB2RVkWkWerW5+KXBeNGWryTB3jkFuTNeOkadFUV/Pwc03/uVPbDwPTgLX1vHrXACA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "admin@mydomain.com"
                        },
                        new
                        {
                            Id = new Guid("77a6570f-3ce5-48ba-9461-80283ed1d94d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81fc5b8e-92f6-4595-8894-03b73599747a",
                            Email = "shadow@mydomain.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SHADOW@MYDOMAIN.COM",
                            NormalizedUserName = "SHADOW@MYDOMAIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHR2Fdj4d21p+TwdrnltoT9jYn7mBRyFteSt2s+8e6HItbar+PByw0pfIIQkb/FV4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "shadow@mydomain.com"
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.UserOrganization", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AwaitingApproval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Blacklisted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateBlacklisted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "OrgId");

                    b.HasIndex("OrgId");

                    b.ToTable("UserOrganizations");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a5570f-3ce5-48ba-9461-80283ed1d94d"),
                            AwaitingApproval = false,
                            Blacklisted = false,
                            DateApproved = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            DateSubmitted = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            UserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            AwaitingApproval = false,
                            Blacklisted = false,
                            DateApproved = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            DateSubmitted = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.UserOrganizationRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "OrgId", "RoleId");

                    b.HasIndex("OrgId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserOrganizationRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a5570f-3ce5-48ba-9461-80283ed1d94d"),
                            RoleId = new Guid("78a7570f-3ce5-48ba-9461-80283ed1d94d")
                        },
                        new
                        {
                            UserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            RoleId = new Guid("78a7570f-3ce5-48ba-9461-80283ed1d94d")
                        },
                        new
                        {
                            UserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a5570f-3ce5-48ba-9461-80283ed1d94d"),
                            RoleId = new Guid("77a7570f-3ce5-48ba-9461-80283ed1d94d")
                        },
                        new
                        {
                            UserId = new Guid("79a7570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            RoleId = new Guid("77a7570f-3ce5-48ba-9461-80283ed1d94d")
                        },
                        new
                        {
                            UserId = new Guid("77a6570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            RoleId = new Guid("78a7570f-3ce5-48ba-9461-80283ed1d94d")
                        },
                        new
                        {
                            UserId = new Guid("77a6570f-3ce5-48ba-9461-80283ed1d94d"),
                            OrgId = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            RoleId = new Guid("77a7570f-3ce5-48ba-9461-80283ed1d94d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Permission", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.PermissionCategory", "PermCategory")
                        .WithMany("Permissions")
                        .HasForeignKey("PermCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermCategory");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Role", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrgId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMultiTenancy.Identity.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.UserOrganization", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.Organization", "Organization")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMultiTenancy.Identity.Entities.User", "User")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.UserOrganizationRole", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.Organization", "Organization")
                        .WithMany("UserOrganizationRoles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMultiTenancy.Identity.Entities.Role", "Role")
                        .WithMany("UserOrganizationRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMultiTenancy.Identity.Entities.User", "User")
                        .WithMany("UserOrganizationRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMultiTenancy.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CoreMultiTenancy.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Organization", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("UserOrganizationRoles");

                    b.Navigation("UserOrganizations");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.PermissionCategory", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserOrganizationRoles");
                });

            modelBuilder.Entity("CoreMultiTenancy.Identity.Entities.User", b =>
                {
                    b.Navigation("UserOrganizationRoles");

                    b.Navigation("UserOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
