// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermissionServerDemo.Api.Data;

#nullable disable

namespace PermissionServerDemo.Api.Migrations
{
    [DbContext(typeof(TenantedDbContext))]
    [Migration("20221119021402_demo")]
    partial class demo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("PermissionServerDemo.Api.Entities.Aircraft", b =>
                {
                    b.Property<string>("RegNumber")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGrounded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShadowOwned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUri")
                        .HasColumnType("TEXT");

                    b.HasKey("RegNumber", "TenantId");

                    b.ToTable("Aircraft");

                    b.HasData(
                        new
                        {
                            RegNumber = "N772GK",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsGlobal = true,
                            IsGrounded = false,
                            IsShadowOwned = false,
                            Model = "Cessna 172S",
                            ThumbnailUri = "N772GK.jpg"
                        },
                        new
                        {
                            RegNumber = "N5342K",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsGlobal = true,
                            IsGrounded = false,
                            IsShadowOwned = true,
                            Model = "Piper Archer",
                            ThumbnailUri = "N5342K.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
