// <auto-generated />
using System;
using CoreMultiTenancy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMultiTenancy.Api.Migrations
{
    [DbContext(typeof(TenantedDbContext))]
    [Migration("20220816225333_demo")]
    partial class demo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("CoreMultiTenancy.Api.Entities.Aircraft", b =>
                {
                    b.Property<string>("RegNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGrounded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUri")
                        .HasColumnType("TEXT");

                    b.HasKey("RegNumber");

                    b.ToTable("Aircraft");

                    b.HasData(
                        new
                        {
                            RegNumber = "N772GK",
                            IsGrounded = false,
                            TenantId = new Guid("77a5570f-3ce5-48ba-9461-80283ed1d94d"),
                            ThumbnailUri = "N772GK.jpg"
                        },
                        new
                        {
                            RegNumber = "N5342K",
                            IsGrounded = false,
                            TenantId = new Guid("77a6550f-3ce5-48ba-9461-80283ed1d94d"),
                            ThumbnailUri = "N5342K.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
